version: "3"
services:
  app:
    image: dirkjkb/python-prometheus-sample:latest
    ports:
      - 80:5000
    restart: always
  prometheus-to-cloudwatch:
    image: cloudposse/prometheus-to-cloudwatch
    restart: always
    environment:
      - CLOUDWATCH_NAMESPACE=prometheus-cloudwatch-pipe
      - CLOUDWATCH_REGION=us-east-1
      - CLOUDWATCH_PUBLISH_TIMEOUT=3
      - PROMETHEUS_SCRAPE_INTERVAL=5
      - PROMETHEUS_SCRAPE_URL=http://app:5000/metrics
